### ISSUE TITLE
TODO Jan 2024

### ISSUE THREAD

**Issue by arnaudbore** [scilus/scilpy#874]
Renaming:
- [x] scil_detect_dwi_volume_outliers.py

- [x] scil_analyse_lesions_load.py -> scil_lesions_info.py.

- [x] scil_group_comparison.py -> scil_stats_group_comparison.py

- [x] scil_compute_metrics_stats_in_ROI.py -> scil_volume_stats_in_ROI.py.

- [x] scil_plot_mean_std_per_point.py -> scil_plot_stats_per_point.py

- [x] AB dipy 1.8 PR

- [x] PK PR

- [x] GG PR

- [ ] Graham PR

- [ ] EM PR

- [ ] Alex visu PR

- [ ] Francois PR

--------------------------

- [x] Template PR

**Comment by EmmaRenauld** [comment]
Haha, your last dashes just highlighted Francois's line!

If we want to keep the template simple, we could just send a link here and say to please follow our standards, and update the doc: https://scil-documentation.readthedocs.io/en/latest/coding/scilpy.html
